server:
  port: 8787
  
spring:
  datasource:
    url: jdbc:mysql://192.168.80.138:3306/urule?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456